{{- if .Values.persistence.persistentVolume }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Release.Name }}-storage-class
  capacity:
    storage: {{ .Values.persistence.size }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  hostPath:
    path: /mnt/{{ .Release.Name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-volumeclaim
spec:
  storageClassName: {{ .Release.Name }}-storage-class
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

{{- end }}

