apiVersion: v1
kind: Service
metadata:
  name: {{ template "mediumlabs.releasename" . }}
  {{- include "mediumlabs.labels" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.applicationPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mediumlabs.selectorlabels" . | nindent 4 }}
